token: ""
searchUrl: "https://api.twitter.com/2/tweets/search/recent?max_results=50&tweet.fields=entities&query="
query:
  required:
  - "news"
  - "lang:en" 
  - "-is:retweet" 
  - "is:verified"
  optional:
  - "nc"
  - "unitedstates"
  - "usa"
  - "world"
  - "science"
  - "math"
  - "space"
  - "tech"
  - "technology"